services:
  git-server:
    image: gitea/gitea:1.22.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__actions__enabled=true
      - GITEA__mailer__ENABLED=false
    restart: always
    networks:
      - gitea
    volumes:
      - ./backup/:/backup/
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    healthcheck:
      test: curl -fSs 127.0.0.1:3000/api/healthz || exit 1
      start_period: 60s
      interval: 5s
      timeout: 10s
      retries: 3

  runner:
    image: gitea/act_runner:0.2.11
    networks:
      - gitea
    depends_on:
      git-server:
        condition: service_healthy
    environment:
      CONFIG_FILE: /config/config.yaml
      GITEA_INSTANCE_URL: "http://git-server:3000"
      GITEA_RUNNER_NAME: "gitea-runner"
      GITEA_RUNNER_LABELS: "ubuntu-latest,linux,docker"
    env_file:
      - runner.env
    volumes:
      - ./services/runner/config/:/config/
      - ./services/runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitea-data:
    driver: local

networks:
  gitea:
    external: false
